export const CURRENT_VERSION = {
    "version": "1.0.0",
    "gateway": "/"
};

export const NAME_TRANS_TABLE = {
    "NOX": "NOx",
    "nox": "NOx",
    "SO2": "SO₂",
    "so2": "SO₂",
    "NO2": "NO₂",
    "no2": "NO₂",
    "O3": "O₃",
    "o3": "O₃",
    "PM10": "PM₁₀",
    "pm10": "PM₁₀",
    "PM2.5": "PM₂.₅",
    "PM25": "PM₂.₅",
    "pm25": "PM₂.₅",
    "aqi": "AQI",
    "CO": "CO",
    "co": "CO",
};

export const NAME_TRANS_WITH_UNIT = {
    "PH值": { name: "PH值", unit: "", unitAir: "" },
    "NOX": { name: "NOx", unit: "mg/m³", unitAir: "(mg/m³)" },
    "SO2": { name: "SO₂", unit: "mg/m³", unitAir: "(μg/m³)" },
    "so2": { name: "SO₂", unit: "mg/m³", unitAir: "(μg/m³)" },
    "颗粒物": { name: "颗粒物", unit: "mg/m³", unitAir: "(mg/m³)" },
    "COD": { name: "COD", unit: "mg/L", unitAir: "(mg/L)" },
    "氨氮": { name: "氨氮", unit: "mg/L", unitAir: "(mg/L)" },
    "CO": { name: "CO", unit: "mg/m³", unitAir: "(mg/m³)" },
    "co": { name: "CO", unit: "mg/m³", unitAir: "(mg/m³)" },
    "NO2": { name: "NO₂", unit: "μg/m³", unitAir: "(μg/m³)" },
    "no2": { name: "NO₂", unit: "μg/m³", unitAir: "(μg/m³)" },
    "O3": { name: "O₃", unit: "μg/m³", unitAir: "(μg/m³)" },
    "o3": { name: "O₃", unit: "μg/m³", unitAir: "(μg/m³)" },
    "PM10": { name: "PM₁₀", unit: "μg/m³", unitAir: "(μg/m³)" },
    "pm10": { name: "PM₁₀", unit: "μg/m³", unitAir: "(μg/m³)" },
    "PM2.5": { name: "PM₂.₅", unit: "μg/m³", unitAir: "(μg/m³)" },
    "pm25": { name: "PM₂.₅", unit: "μg/m³", unitAir: "(μg/m³)" },
    "AQI": { name: "AQI", unit: " ", unitAir: "" },
    "水质类别": { name: "水质类别", unit: " ", unitAir: "" },
    "溶解氧": { name: "溶解氧", unit: "mg/L", unitAir: "(mg/L)" },
    "高锰酸盐指数": { name: "高锰酸盐指数", unit: "mg/L", unitAir: "(mg/L)" },
    "pH": { name: "pH", unit: " ", unitAir: "" },
    "流量": { name: "流量", unit: "L/S", unitAir: "(L/S)" },
    "烟尘": { name: "烟尘", unit: "mg/m³", unitAir: "(mg/m³)" },
    "烟尘流量": { name: "烟尘流量", unit: "m³/S", unitAir: "(m³/S)" },
}; 
